apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${artifactId}-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${artifactId}
  template:
    metadata:
      labels:
        app: ${artifactId}
    spec:
      containers:
      - name: ${artifactId}
        image: ortaieb/${artifactId}:${version}
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /q/health/ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
      - name: mesh-module
        image: ortaieb/platform-module:0.0.1
        ports:
        - containerPort: 8090
        env:
        - name: ENV_EXAMPLE_KEY
          value: "env_example_value"
        readinessProbe:
          httpGet:
            path: /q/health/ready
            port: 8090
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: ${artifactId}-svc
spec:
  selector:
    app: ${artifactId}
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
  type: NodePort
